swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: 'test&quot;&gt;xss&lt;div&gt;test&lt;/div&gt;'
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET

